#include <molto/project/lockfile.h>

#include <molto/services/fs_service.h>
#include <molto/util/str_map.h>
#include <molto/util/toml.h>

#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Which build a locked package belongs to (RFC-0008). Both, for one required
   by `[deps]` and `[dev-deps]` alike: it is one package at one version, and
   the array says which builds reach it — so a production install can fetch
   only what it links. */
#define SCOPE_RUNTIME "runtime"
#define SCOPE_DEV "dev"

/* The file whose edits make a lock stale, named in the message that says so. */
#define MANIFEST_FILENAME "Project.toml"

/* Grown as needed; the initial size holds a small graph without a realloc. */
#define RENDER_INITIAL 4096

/* --- a growable string --- */

typedef struct {
    char *text;
    size_t length;
    size_t capacity;
} buffer;

static bool buffer_reserve(buffer *out, size_t extra) {
    if(out->length + extra + 1 <= out->capacity)
        return true;
    size_t grown = out->capacity == 0 ? RENDER_INITIAL : out->capacity;
    while(grown < out->length + extra + 1)
        grown *= 2;
    char *text = realloc(out->text, grown);
    if(text == NULL)
        return false;
    out->text = text;
    out->capacity = grown;
    return true;
}

static bool buffer_puts(buffer *out, const char *text) {
    const size_t length = strlen(text);
    if(!buffer_reserve(out, length))
        return false;
    memcpy(out->text + out->length, text, length + 1);
    out->length += length;
    return true;
}

/* A TOML basic string. Paths and URLs reach this, and one of them will
   eventually carry a quote or a backslash; a lock file that stops parsing at
   that point would be found by whoever wrote the path, long after. */
static bool buffer_put_quoted(buffer *out, const char *value) {
    if(!buffer_puts(out, "\""))
        return false;
    for(const char *p = value; *p != '\0'; p++) {
        char escaped[3] = {*p, '\0', '\0'};
        if(*p == '"' || *p == '\\') {
            escaped[0] = '\\';
            escaped[1] = *p;
        }
        if(!buffer_puts(out, escaped))
            return false;
    }
    return buffer_puts(out, "\"");
}

static bool buffer_put_pair(buffer *out, const char *key, const char *value) {
    return buffer_puts(out, key) && buffer_puts(out, " = ") && buffer_put_quoted(out, value) &&
           buffer_puts(out, "\n");
}

static bool buffer_put_list(buffer *out, const char *key, const str_list *values) {
    if(!buffer_puts(out, key) || !buffer_puts(out, " = ["))
        return false;
    for(size_t i = 0; i < str_list_count(values); i++) {
        if(i > 0 && !buffer_puts(out, ", "))
            return false;
        if(!buffer_put_quoted(out, str_list_get(values, i)))
            return false;
    }
    return buffer_puts(out, "]\n");
}

/* --- writing --- */

char *lockfile_render(const char *package, const dep_graph *graph, const lock_host *hosts,
                      size_t host_count) {
    buffer out = {0};
    char header[64];
    snprintf(header, sizeof header, "version = %d\n", LOCKFILE_VERSION);

    bool ok = buffer_puts(&out, "# Generated by molto. Committed on purpose: it is what makes a\n"
                                "# build on another machine contain the same bytes as this one.\n"
                                "# Edit Project.toml, not this file.\n\n") &&
              buffer_puts(&out, header) && buffer_put_pair(&out, "root", package);

    for(size_t i = 0; ok && i < dep_graph_count(graph); i++) {
        const dep_node *node = dep_graph_at(graph, i);
        /* Ordered, not as encountered: runtime before dev, always, so the diff
           of a regenerated lock stays empty. */
        str_list scopes;
        str_list_init(&scopes);
        ok = true;
        if(node->scope & dep_scope_runtime)
            ok = str_list_push(&scopes, SCOPE_RUNTIME);
        if(ok && (node->scope & dep_scope_dev))
            ok = str_list_push(&scopes, SCOPE_DEV);
        ok =
            ok && buffer_puts(&out, "\n[[package]]\n") && buffer_put_pair(&out, "name", node->name);
        /* A version is omitted rather than written empty: a path dependency has
           none, and "" would read as a version that happens to be blank. */
        if(ok && node->version[0] != '\0')
            ok = buffer_put_pair(&out, "version", node->version);
        if(ok)
            ok = buffer_put_pair(&out, "source", node->source);
        if(ok && node->checksum[0] != '\0')
            ok = buffer_put_pair(&out, "checksum", node->checksum);
        if(ok)
            ok = buffer_put_list(&out, "scopes", &scopes) &&
                 buffer_put_list(&out, "dependencies", &node->dependencies);
        str_list_free(&scopes);
    }

    /* After the packages, because that is the order a reader wants: what this
       build contains, then what it borrowed from the machine it was built on. */
    for(size_t i = 0; ok && i < host_count; i++) {
        ok = buffer_puts(&out, "\n[[host]]\n") &&
             buffer_put_pair(&out, "capability", hosts[i].capability) &&
             buffer_put_pair(&out, "answered", hosts[i].answered);
        /* Omitted rather than written empty, like a package's version and for
           the same reason: "" reads as a version that happens to be blank. */
        if(ok && hosts[i].version[0] != '\0')
            ok = buffer_put_pair(&out, "version", hosts[i].version);
    }

    if(!ok) {
        free(out.text);
        return NULL;
    }
    return out.text;
}

static bool set_error(char *err, size_t err_size, const char *format, ...)
    __attribute__((format(printf, 3, 4)));

static bool set_error(char *err, size_t err_size, const char *format, ...) {
    if(err != NULL && err_size > 0) {
        va_list args;
        va_start(args, format);
        (void)vsnprintf(err, err_size, format, args);
        va_end(args);
    }
    return false;
}

static bool lock_path(const char *root, char *out, size_t out_size, char *err, size_t err_size) {
    if(!fs_format_path(out, out_size, "%s/" LOCKFILE_NAME, root))
        return set_error(err, err_size, "the path to " LOCKFILE_NAME " is too long");
    return true;
}

bool lockfile_write(const char *root, const char *package, const dep_graph *graph,
                    const lock_host *hosts, size_t host_count, char *err, size_t err_size) {
    char path[1024];
    if(!lock_path(root, path, sizeof path, err, err_size))
        return false;

    char *text = lockfile_render(package, graph, hosts, host_count);
    if(text == NULL)
        return set_error(err, err_size, "out of memory writing " LOCKFILE_NAME);

    const bool ok = fs_write_file(path, text);
    free(text);
    return ok ? true : set_error(err, err_size, "could not write %s", path);
}

/* --- reading --- */

static void package_init(lock_package *out) {
    memset(out->name, 0, sizeof out->name);
    memset(out->version, 0, sizeof out->version);
    memset(out->source, 0, sizeof out->source);
    memset(out->checksum, 0, sizeof out->checksum);
    str_list_init(&out->scopes);
    str_list_init(&out->dependencies);
}

static bool read_package(const toml_document *doc, const char *section, lock_package *out,
                         char *err, size_t err_size) {
    package_init(out);
    if(!toml_get_string(doc, section, "name", out->name, sizeof out->name))
        return set_error(err, err_size, LOCKFILE_NAME ": a [[package]] has no name");
    if(!toml_get_string(doc, section, "source", out->source, sizeof out->source))
        return set_error(err, err_size, LOCKFILE_NAME ": '%s' has no source", out->name);
    if(!toml_get_string(doc, section, "version", out->version, sizeof out->version))
        out->version[0] = '\0';
    if(!toml_get_string(doc, section, "checksum", out->checksum, sizeof out->checksum))
        out->checksum[0] = '\0';
    (void)toml_get_array(doc, section, "scopes", &out->scopes);
    (void)toml_get_array(doc, section, "dependencies", &out->dependencies);
    return true;
}

bool lockfile_read(const char *root, lockfile *out, char *err, size_t err_size) {
    memset(out, 0, sizeof *out);

    char path[1024];
    if(!lock_path(root, path, sizeof path, err, err_size))
        return false;
    if(!fs_path_exists(path))
        return set_error(err, err_size, "there is no " LOCKFILE_NAME " yet");

    char *text = fs_read_file(path);
    if(text == NULL)
        return set_error(err, err_size, "could not read %s", path);

    char parse_err[256] = "";
    toml_document *doc = toml_parse(text, parse_err, sizeof parse_err);
    free(text);
    if(doc == NULL)
        return set_error(err, err_size, "%s is not valid TOML: %s", path, parse_err);

    bool ok = toml_get_int(doc, "", "version", &out->version);
    if(!ok)
        ok = set_error(err, err_size, LOCKFILE_NAME " declares no format version");
    /* A newer format may give an existing key a new meaning, so a reader that
       proceeds anyway is confidently wrong. Re-resolving is always available
       and always correct. */
    else if(out->version != LOCKFILE_VERSION)
        ok = set_error(err, err_size, LOCKFILE_NAME " is version %ld and this molto writes %d",
                       out->version, LOCKFILE_VERSION);
    if(ok && !toml_get_string(doc, "", "root", out->root, sizeof out->root))
        ok = set_error(err, err_size, LOCKFILE_NAME " does not say which package it belongs to");

    const size_t total = ok ? toml_table_array_count(doc, "package") : 0;
    if(ok && total > 0) {
        out->packages = calloc(total, sizeof *out->packages);
        if(out->packages == NULL)
            ok = set_error(err, err_size, "out of memory reading " LOCKFILE_NAME);
    }

    for(size_t i = 0; ok && i < total; i++) {
        char section[TOML_SECTION_MAX];
        ok = toml_table_array_section("package", i, section, sizeof section) &&
             read_package(doc, section, &out->packages[i], err, err_size);
        if(ok)
            out->count++;
    }

    const size_t hosts = ok ? toml_table_array_count(doc, "host") : 0;
    if(ok && hosts > 0) {
        out->hosts = calloc(hosts, sizeof *out->hosts);
        if(out->hosts == NULL)
            ok = set_error(err, err_size, "out of memory reading " LOCKFILE_NAME);
    }

    for(size_t i = 0; ok && i < hosts; i++) {
        char section[TOML_SECTION_MAX];
        lock_host *entry = &out->hosts[i];
        ok = toml_table_array_section("host", i, section, sizeof section) &&
             toml_get_string(doc, section, "capability", entry->capability,
                             sizeof entry->capability) &&
             toml_get_string(doc, section, "answered", entry->answered, sizeof entry->answered);
        if(!ok) {
            ok = set_error(err, err_size, LOCKFILE_NAME " has a [[host]] with no capability");
            break;
        }
        /* Absent is allowed and means the resolver knew of no version. */
        if(!toml_get_string(doc, section, "version", entry->version, sizeof entry->version))
            entry->version[0] = '\0';
        out->host_count++;
    }

    toml_free(doc);
    if(!ok)
        lockfile_free(out);
    return ok;
}

size_t lockfile_report_host_drift(const lockfile *lock, const lock_host *hosts, size_t host_count) {
    size_t drifted = 0;
    for(size_t i = 0; i < host_count; i++) {
        for(size_t j = 0; j < lock->host_count; j++) {
            if(strcmp(lock->hosts[j].capability, hosts[i].capability) != 0)
                continue;
            /* Nothing to say when either side has no version: a `.pc` file may
               omit one, and "it changed to unknown" is not a fact worth a line
               of a build's output. */
            if(lock->hosts[j].version[0] == '\0' || hosts[i].version[0] == '\0')
                break;
            if(strcmp(lock->hosts[j].version, hosts[i].version) == 0)
                break;
            fprintf(stderr,
                    "molto: note: the host library '%s' is %s here and %s in " LOCKFILE_NAME
                    "; molto neither installs nor pins one, so this build used what is "
                    "installed\n",
                    hosts[i].capability, hosts[i].version, lock->hosts[j].version);
            drifted++;
            break;
        }
    }
    return drifted;
}

/* --- staleness --- */

static const lock_package *find_package(const lockfile *lock, const char *name) {
    for(size_t i = 0; i < lock->count; i++) {
        if(strcmp(lock->packages[i].name, name) == 0)
            return &lock->packages[i];
    }
    return NULL;
}

/* Mark everything reachable from `name` through the lock's own edges. */
static bool mark_reachable(const lockfile *lock, const char *name, str_map *seen) {
    if(str_map_get(seen, name) != NULL)
        return true;
    const lock_package *locked = find_package(lock, name);
    if(locked == NULL)
        return true; /* the caller already refused it */
    if(!str_map_put(seen, name, (void *)locked))
        return false;
    for(size_t i = 0; i < str_list_count(&locked->dependencies); i++) {
        if(!mark_reachable(lock, str_list_get(&locked->dependencies, i), seen))
            return false;
    }
    return true;
}

bool lockfile_matches(const lockfile *lock, const project_ctx *ctx) {
    if(strcmp(lock->root, ctx->project_name) != 0)
        return false;

    /* Every direct dependency has to be locked, at the version the manifest
       now names. The transitive ones cannot have moved without one of these
       moving too: a recipe is published once and a coordinate is immutable
       (RFC-0010). */
    for(size_t i = 0; i < ctx->deps.count; i++) {
        const project_dep *dep = &ctx->deps.items[i];
        const lock_package *locked = find_package(lock, dep->name);
        if(locked == NULL)
            return false;
        if(dep->resolution == dep_resolution_registry && strcmp(locked->version, dep->version) != 0)
            return false;
    }

    /* And nothing may be locked that the manifest no longer reaches. Checking
       only the direct entries would call a lock still valid after a dependency
       was removed, and the build would keep compiling what the manifest
       dropped. The lock's own edges answer this without a network. */
    str_map *seen = str_map_create(NULL);
    if(seen == NULL)
        return false;
    bool ok = true;
    for(size_t i = 0; ok && i < ctx->deps.count; i++)
        ok = mark_reachable(lock, ctx->deps.items[i].name, seen);
    const bool complete = ok && str_map_size(seen) == lock->count;
    str_map_destroy(seen);
    return complete;
}

/* --- verifying --- */

bool lockfile_verify(const lockfile *lock, const dep_graph *graph, char *err, size_t err_size) {
    for(size_t i = 0; i < dep_graph_count(graph); i++) {
        const dep_node *node = dep_graph_at(graph, i);
        const lock_package *locked = find_package(lock, node->name);

        /* A package the lock never saw, on a manifest that has not changed,
           means something upstream grew a dependency under a coordinate that
           was supposed to be frozen. */
        if(locked == NULL)
            return set_error(
                err, err_size,
                "'%s' is in this build and not in " LOCKFILE_NAME ", though " MANIFEST_FILENAME
                " has not changed. Something it depends on "
                "changed what *it* depends on. Check the diff, then delete " LOCKFILE_NAME
                " to accept it",
                node->name);

        if(strcmp(locked->version, node->version) != 0)
            return set_error(err, err_size,
                             "'%s' resolves to version '%s' and " LOCKFILE_NAME " records '%s'",
                             node->name, node->version, locked->version);
        if(strcmp(locked->source, node->source) != 0)
            return set_error(err, err_size,
                             "'%s' now comes from %s and " LOCKFILE_NAME " records %s", node->name,
                             node->source, locked->source);
        /* A checksum only one side has is not a mismatch: a path dependency
           has none, and neither did a lock written before one was recorded. */
        if(locked->checksum[0] != '\0' && node->checksum[0] != '\0' &&
           strcmp(locked->checksum, node->checksum) != 0)
            return set_error(err, err_size,
                             "'%s' %s hashes to %s and " LOCKFILE_NAME " records %s. The same "
                             "coordinate served different bytes",
                             node->name, node->version, node->checksum, locked->checksum);
    }
    return true;
}

void lockfile_free(lockfile *lock) {
    for(size_t i = 0; i < lock->count; i++) {
        str_list_free(&lock->packages[i].scopes);
        str_list_free(&lock->packages[i].dependencies);
    }
    free(lock->packages);
    lock->packages = NULL;
    lock->count = 0;
    free(lock->hosts);
    lock->hosts = NULL;
    lock->host_count = 0;
}
